---

- name: "Download wordpress"
  get_url: 
    url: "{{ url }}"
    dest: /tmp/wordpress.tar.gz
        
- name: "Extract wordpress tar file"
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp/
    remote_src: true
        
- name: "Copy website files to document root"
  copy:
    src: /tmp/wordpress/
    dest: "/var/www/html/{{ httpd_domain }}/"
    remote_src: true
    owner: "{{ httpd_owner }}"
    group: "{{ httpd_group }}"
        
- name: "Update Wp-Config.php"
  template:
    src: wp-config.php.tmpl
    dest: "/var/www/html/{{ httpd_domain }}/wp-config.php"
    owner: "{{ httpd_owner }}"
    group: "{{ httpd_group }}"
        
        
- name: "Restart"
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  with_items:
    - httpd
    - mariadb
    
- name: "Clean files after installation"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/wordpress/
    - /tmp/wordpress.tar.gz
